name: Check eslint, prettier and npm audit.
env:
  IMAGE_VERSION: ${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - main
  workflow_call: {}

jobs:
  run-eslint:
    name: Run Eslint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run eslint check
        run: npm run lint:check

  run-prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    needs: run-eslint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run prettier check
        run: npm run prettier:check

  run-npm-audit:
    name: Run Npm Audit
    runs-on: ubuntu-latest
    needs: run-prettier
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high
